name: Generate HTML

on:
  schedule:
    - cron: '15 * * * *'  # Runs 15 minutes past
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML
      run: python blogmarks/render.py

    - name: Commit HTML files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add _site/
        if ! git diff-index --quiet HEAD --; then
          git commit -m 'Generate HTML files'
          git push
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
